use psycopg 3 adapter again
This is for postgres re: commit f855cefe1e59bd9d788c07a5ae0ce43adf716bf9

Also sets `"client_encoding": "utf-8"` due to the error when trying to
connect to redshift:
    sqlalchemy.exc.NotSupportedError: (psycopg.NotSupportedError) codec not available in Python: 'UNICODE'